services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./backend:/home/root/app
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    networks:
      - internal

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - internal

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: on-failure
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./frontend:/home/root/app
    env_file:
      - ./frontend/.env
    networks:
      - internal

networks:
  internal:
    driver: bridge
